const TOPICS = [
  {
    id: "environnement",
    fr: "L'environnement",
    en: "The Environment",
    icon: "\u{1F33F}",
    available: true,
    words: [
      {
        cat: "Nature (la terre)",
        article: "une",
        word: "montagne",
        meaning: "mountain",
        fr: "J'aime faire de la randonn\u00e9e en montagne le week-end.",
        en: "I like hiking in the mountains on weekends.",
      },
      {
        cat: "Nature (la terre)",
        article: "une",
        word: "colline",
        meaning: "hill",
        fr: "Il y a une petite colline pr\u00e8s de chez moi.",
        en: "There is a small hill near my home.",
      },
      {
        cat: "Nature (la terre)",
        article: "une",
        word: "plaine",
        meaning: "flat land",
        fr: "La plaine est id\u00e9ale pour l'agriculture.",
        en: "The plain is ideal for agriculture.",
      },
      {
        cat: "Nature (la terre)",
        article: "une",
        word: "for\u00eat",
        meaning: "forest",
        fr: "La for\u00eat est calme et tr\u00e8s relaxante.",
        en: "The forest is calm and very relaxing.",
      },
      {
        cat: "Nature (la terre)",
        article: "un",
        word: "sentier",
        meaning: "path / trail",
        fr: "Je marche souvent sur des sentiers en nature.",
        en: "I often walk on trails in nature.",
      },
      {
        cat: "Nature (la terre)",
        article: "un",
        word: "torrent",
        meaning: "fast mountain stream",
        fr: "Le torrent descend rapidement de la montagne.",
        en: "The stream flows quickly down the mountain.",
      },
      {
        cat: "Eau (inland)",
        article: "un",
        word: "lac",
        meaning: "lake",
        fr: "Le lac est tr\u00e8s paisible et propre.",
        en: "The lake is very peaceful and clean.",
      },
      {
        cat: "Eau (inland)",
        article: "une",
        word: "rivi\u00e8re",
        meaning: "river (small)",
        fr: "Une rivi\u00e8re traverse le village.",
        en: "A river runs through the village.",
      },
      {
        cat: "Eau (inland)",
        article: "un",
        word: "fleuve",
        meaning: "large river to the sea",
        fr: "Le Gange est un grand fleuve en Asie.",
        en: "The Ganges is a large river in Asia.",
      },
      {
        cat: "La mer",
        article: "la",
        word: "mer",
        meaning: "sea",
        fr: "J'adore passer du temps au bord de la mer.",
        en: "I love spending time by the sea.",
      },
      {
        cat: "La mer",
        article: "une",
        word: "vague",
        meaning: "wave",
        fr: "Les vagues sont fortes aujourd'hui.",
        en: "The waves are strong today.",
      },
      {
        cat: "La mer",
        article: "une",
        word: "plage",
        meaning: "beach",
        fr: "La plage est parfaite pour se d\u00e9tendre.",
        en: "The beach is perfect for relaxing.",
      },
      {
        cat: "La mer",
        article: "une",
        word: "crique",
        meaning: "small bay / cove",
        fr: "Nous avons trouv\u00e9 une petite crique tranquille.",
        en: "We found a small quiet bay.",
      },
      {
        cat: "La mer",
        article: "la",
        word: "c\u00f4te",
        meaning: "coast",
        fr: "La c\u00f4te est magnifique au coucher du soleil.",
        en: "The coast is beautiful at sunset.",
      },
      {
        cat: "La mer",
        article: "une",
        word: "falaise",
        meaning: "cliff",
        fr: "La falaise est tr\u00e8s impressionnante.",
        en: "The cliff is very impressive.",
      },
      {
        cat: "La mer",
        article: "une",
        word: "dune",
        meaning: "sand dune",
        fr: "Les dunes sont typiques dans le d\u00e9sert.",
        en: "Sand dunes are typical in the desert.",
      },
      {
        cat: "La campagne",
        article: "un",
        word: "village",
        meaning: "village",
        fr: "Je pr\u00e9f\u00e8re vivre dans un village calme.",
        en: "I prefer to live in a quiet village.",
      },
      {
        cat: "La campagne",
        article: "un",
        word: "champ",
        meaning: "field (farming)",
        fr: "Les agriculteurs travaillent dans les champs.",
        en: "Farmers work in the fields.",
      },
      {
        cat: "La campagne",
        article: "un",
        word: "pr\u00e9",
        meaning: "meadow (animals)",
        fr: "Les vaches sont dans le pr\u00e9.",
        en: "The cows are in the meadow.",
      },
      {
        cat: "Ph\u00e9nom\u00e8nes naturels",
        article: "un",
        word: "volcan",
        meaning: "volcano",
        fr: "Ce volcan est encore actif.",
        en: "This volcano is still active.",
      },
      {
        cat: "Ph\u00e9nom\u00e8nes naturels",
        article: "une",
        word: "\u00e9ruption volcanique",
        meaning: "volcanic eruption",
        fr: "L'\u00e9ruption volcanique est dangereuse.",
        en: "The volcanic eruption is dangerous.",
      },
      {
        cat: "Ph\u00e9nom\u00e8nes naturels",
        article: "un",
        word: "d\u00e9sert",
        meaning: "desert",
        fr: "Le d\u00e9sert est tr\u00e8s sec et chaud.",
        en: "The desert is very dry and hot.",
      },
      {
        cat: "Ph\u00e9nom\u00e8nes naturels",
        article: "la",
        word: "v\u00e9g\u00e9tation",
        meaning: "vegetation / plants",
        fr: "Il y a peu de v\u00e9g\u00e9tation dans cette r\u00e9gion.",
        en: "There is little vegetation in this region.",
      },
      {
        cat: "Ph\u00e9nom\u00e8nes naturels",
        article: "l'",
        word: "\u00e9rosion",
        meaning: "erosion",
        fr: "L'\u00e9rosion change le paysage avec le temps.",
        en: "Erosion changes the landscape over time.",
      },
      {
        cat: "G\u00e9ographie",
        article: "un",
        word: "oc\u00e9an",
        meaning: "ocean",
        fr: "L'oc\u00e9an Pacifique est le plus grand.",
        en: "The Pacific Ocean is the largest.",
      },
      {
        cat: "G\u00e9ographie",
        article: "une",
        word: "mer",
        meaning: "sea",
        fr: "La mer M\u00e9diterran\u00e9e est tr\u00e8s connue.",
        en: "The Mediterranean Sea is very well known.",
      },
      {
        cat: "G\u00e9ographie",
        article: "un",
        word: "continent",
        meaning: "continent",
        fr: "L'Asie est le plus grand continent.",
        en: "Asia is the largest continent.",
      },
      {
        cat: "G\u00e9ographie",
        article: "une",
        word: "\u00eele",
        meaning: "island",
        fr: "Je r\u00eave de visiter une \u00eele tropicale.",
        en: "I dream of visiting a tropical island.",
      },
      {
        cat: "G\u00e9ographie",
        article: "une",
        word: "fronti\u00e8re",
        meaning: "border",
        fr: "La fronti\u00e8re s\u00e9pare deux pays.",
        en: "The border separates two countries.",
      },
      {
        cat: "Concepts terrestres",
        article: "l'",
        word: "\u00e9quateur",
        meaning: "equator",
        fr: "L'\u00e9quateur traverse plusieurs pays.",
        en: "The equator crosses several countries.",
      },
      {
        cat: "Concepts terrestres",
        article: "un",
        word: "p\u00f4le",
        meaning: "pole",
        fr: "Le p\u00f4le Nord est tr\u00e8s froid.",
        en: "The North Pole is very cold.",
      },
      {
        cat: "Concepts terrestres",
        article: "un",
        word: "h\u00e9misph\u00e8re",
        meaning: "hemisphere",
        fr: "Le Canada est dans l'h\u00e9misph\u00e8re nord.",
        en: "Canada is in the northern hemisphere.",
      },
      {
        cat: "Concepts terrestres",
        article: "un",
        word: "tropique",
        meaning: "tropic",
        fr: "Le climat est chaud pr\u00e8s des tropiques.",
        en: "The climate is warm near the tropics.",
      },
      {
        cat: "Concepts terrestres",
        article: "les",
        word: "points cardinaux",
        meaning: "cardinal directions",
        fr: "On utilise les points cardinaux pour s'orienter.",
        en: "We use cardinal directions to navigate.",
      },
    ],
    collocations: [],
    phrases: [],
  },
  {
    id: "education",
    fr: "L'\u00e9ducation",
    en: "Education",
    icon: "\u{1F4DA}",
    available: false,
    words: [],
    collocations: [],
    phrases: [],
  },
  {
    id: "sante",
    fr: "La sant\u00e9",
    en: "Health",
    icon: "\u{1FA7A}",
    available: false,
    words: [],
    collocations: [],
    phrases: [],
  },
  {
    id: "internet",
    fr: "L'internet",
    en: "The Internet",
    icon: "\u{1F4BB}",
    available: false,
    words: [],
    collocations: [],
    phrases: [],
  },
  {
    id: "voyage",
    fr: "Le voyage",
    en: "Travel",
    icon: "\u2708\uFE0F",
    available: false,
    words: [],
    collocations: [],
    phrases: [],
  },
  {
    id: "travail",
    fr: "Le travail",
    en: "Work",
    icon: "\u{1F4BC}",
    available: false,
    words: [],
    collocations: [],
    phrases: [],
  },
];
